# Target executable
TARGET = disk

# Source files
SRCS = diskhash.c test.c

# Object files
OBJS = $(SRCS:.c=.o)

# Default target
all: $(TARGET)

# Link the object files to create the executable
$(TARGET): $(OBJS)
        $(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Compile source files into object files
%.o: %.c
        $(CC) $(CFLAGS) -c $< -o $@

# Clean up build files
clean:
        rm -f $(TARGET) $(OBJS)

# Indicate phony targets
.PHONY: all clean                                    